# name: Flexoki Dark
# url: https://stephango.com/flexoki

[dark]
# preferred_background: 100f0f

fish_color_normal cecdc3
fish_color_command da702c
fish_color_keyword 879a39
fish_color_quote 3aa99f
fish_color_redirection ce5d97
fish_color_end ce5d97
fish_color_error d14d41
fish_color_param 4385be
fish_color_operator 878580
fish_color_comment 575653

# Optional-but-useful core states
fish_color_autosuggestion 575653
fish_color_search_match cecdc3 --background=282726
fish_color_selection cecdc3 --background=282726
fish_color_valid_path --underline
fish_color_escape 3aa99f
fish_color_history_current --bold
fish_color_status d14d41
fish_color_cancel -r

# Pager/completion menu
fish_pager_color_description b7b5ac
fish_pager_color_prefix da702c --bold
fish_pager_color_progress 878580
fish_pager_color_selected_prefix 100f0f
fish_pager_color_selected_completion 1c1b1a
fish_pager_color_selected_description 282726
fish_pager_color_selected_background --background=cecdc3
